version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean install -X
  post_build:
    commands:
      - echo Build completed
      - mvn package
artifacts:
  files:
    - target
    - scripts
    - appspec.yml
  discard-paths: yes